default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  user: postgres
  password: paress10
  port: 5433

development:
  <<: *default
  database: urasuru_development

test:
  <<: *default
  database: urasuru_test

production:
  <<: *default
  database: urasuru_production
